include(ExternalProject)

string(REPLACE ";" "$<SEMICOLON>" CMAKE_OSX_ARCHITECTURES_ "${CMAKE_OSX_ARCHITECTURES}")

if(MSVC)
  if(${CMAKE_GENERATOR_PLATFORM} STREQUAL x64
     AND ${MSVC_VERSION} GREATER_EQUAL 1910
     AND ${MSVC_VERSION} LESS_EQUAL 1939)
    set(AWS_SDK_LIB_PATH x64/vc17/staticlib)
  else()
    message(FATAL_ERROR "Unsupported MSVC!")
  endif()
else()
  set(AWS_SDK_LIB_PATH lib)
  set(AWS_SDK_LIB_SUFFIX "")
endif()

ExternalProject_Add(
  libawscpp-download
  GIT_REPOSITORY https://github.com/aws/aws-sdk-cpp.git
  GIT_TAG 1.11.113
  LIST_SEPARATOR "|"
  CMAKE_GENERATOR ${CMAKE_GENERATOR}
  BUILD_BYPRODUCTS
    <INSTALL_DIR>/${AWS_SDK_LIB_PATH}/${CMAKE_STATIC_LIBRARY_PREFIX}aws-c-auth${AWS_SDK_LIB_SUFFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
    <INSTALL_DIR>/${AWS_SDK_LIB_PATH}/${CMAKE_STATIC_LIBRARY_PREFIX}aws-c-cal${AWS_SDK_LIB_SUFFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
    <INSTALL_DIR>/${AWS_SDK_LIB_PATH}/${CMAKE_STATIC_LIBRARY_PREFIX}aws-c-common${AWS_SDK_LIB_SUFFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
    <INSTALL_DIR>/${AWS_SDK_LIB_PATH}/${CMAKE_STATIC_LIBRARY_PREFIX}aws-c-compression${AWS_SDK_LIB_SUFFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
    <INSTALL_DIR>/${AWS_SDK_LIB_PATH}/${CMAKE_STATIC_LIBRARY_PREFIX}aws-c-event-stream${AWS_SDK_LIB_SUFFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
    <INSTALL_DIR>/${AWS_SDK_LIB_PATH}/${CMAKE_STATIC_LIBRARY_PREFIX}aws-c-http${AWS_SDK_LIB_SUFFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
    <INSTALL_DIR>/${AWS_SDK_LIB_PATH}/${CMAKE_STATIC_LIBRARY_PREFIX}aws-c-io${AWS_SDK_LIB_SUFFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
    <INSTALL_DIR>/${AWS_SDK_LIB_PATH}/${CMAKE_STATIC_LIBRARY_PREFIX}aws-c-mqtt${AWS_SDK_LIB_SUFFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
    <INSTALL_DIR>/${AWS_SDK_LIB_PATH}/${CMAKE_STATIC_LIBRARY_PREFIX}aws-c-s3${AWS_SDK_LIB_SUFFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
    <INSTALL_DIR>/${AWS_SDK_LIB_PATH}/${CMAKE_STATIC_LIBRARY_PREFIX}aws-c-sdkutils${AWS_SDK_LIB_SUFFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
    <INSTALL_DIR>/${AWS_SDK_LIB_PATH}/${CMAKE_STATIC_LIBRARY_PREFIX}aws-checksums${AWS_SDK_LIB_SUFFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
    <INSTALL_DIR>/${AWS_SDK_LIB_PATH}/${CMAKE_STATIC_LIBRARY_PREFIX}aws-cpp-sdk-core${AWS_SDK_LIB_SUFFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
    <INSTALL_DIR>/${AWS_SDK_LIB_PATH}/${CMAKE_STATIC_LIBRARY_PREFIX}aws-cpp-sdk-xray${AWS_SDK_LIB_SUFFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
    <INSTALL_DIR>/${AWS_SDK_LIB_PATH}/${CMAKE_STATIC_LIBRARY_PREFIX}aws-crt-cpp${AWS_SDK_LIB_SUFFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
  CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=<INSTALL_DIR>
             -DBUILD_SHARED_LIBS=OFF
             -DCMAKE_GENERATOR_PLATFORM=${CMAKE_GENERATOR_PLATFORM}
             -DCMAKE_OSX_DEPLOYMENT_TARGET=10.13
             -DCMAKE_OSX_ARCHITECTURES=${CMAKE_OSX_ARCHITECTURES_}
             -DBUILD_ONLY=xray
             -DAWS_COMPILER_WARNINGS=-Wno-shorten-64-to-32
             -DMINIMIZE_SIZE=ON
             -DENABLE_TESTING=OFF
  TEST_COMMAND ""
  BUILD_ALWAYS OFF)

ExternalProject_Get_Property(libawscpp-download INSTALL_DIR)

add_library(libawscpp INTERFACE)
add_dependencies(libawscpp libawscpp-download)
target_link_libraries(
  OpenCV
  INTERFACE
    ${INSTALL_DIR}/${AWS_SDK_LIB_PATH}/${CMAKE_STATIC_LIBRARY_PREFIX}aws-c-auth${AWS_SDK_LIB_SUFFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
    ${INSTALL_DIR}/${AWS_SDK_LIB_PATH}/${CMAKE_STATIC_LIBRARY_PREFIX}aws-c-cal${AWS_SDK_LIB_SUFFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
    ${INSTALL_DIR}/${AWS_SDK_LIB_PATH}/${CMAKE_STATIC_LIBRARY_PREFIX}aws-c-common${AWS_SDK_LIB_SUFFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
    ${INSTALL_DIR}/${AWS_SDK_LIB_PATH}/${CMAKE_STATIC_LIBRARY_PREFIX}aws-c-compression${AWS_SDK_LIB_SUFFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
    ${INSTALL_DIR}/${AWS_SDK_LIB_PATH}/${CMAKE_STATIC_LIBRARY_PREFIX}aws-c-event-stream${AWS_SDK_LIB_SUFFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
    ${INSTALL_DIR}/${AWS_SDK_LIB_PATH}/${CMAKE_STATIC_LIBRARY_PREFIX}aws-c-http${AWS_SDK_LIB_SUFFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
    ${INSTALL_DIR}/${AWS_SDK_LIB_PATH}/${CMAKE_STATIC_LIBRARY_PREFIX}aws-c-io${AWS_SDK_LIB_SUFFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
    ${INSTALL_DIR}/${AWS_SDK_LIB_PATH}/${CMAKE_STATIC_LIBRARY_PREFIX}aws-c-mqtt${AWS_SDK_LIB_SUFFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
    ${INSTALL_DIR}/${AWS_SDK_LIB_PATH}/${CMAKE_STATIC_LIBRARY_PREFIX}aws-c-s3${AWS_SDK_LIB_SUFFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
    ${INSTALL_DIR}/${AWS_SDK_LIB_PATH}/${CMAKE_STATIC_LIBRARY_PREFIX}aws-c-sdkutils${AWS_SDK_LIB_SUFFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
    ${INSTALL_DIR}/${AWS_SDK_LIB_PATH}/${CMAKE_STATIC_LIBRARY_PREFIX}aws-checksums${AWS_SDK_LIB_SUFFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
    ${INSTALL_DIR}/${AWS_SDK_LIB_PATH}/${CMAKE_STATIC_LIBRARY_PREFIX}aws-cpp-sdk-core${AWS_SDK_LIB_SUFFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
    ${INSTALL_DIR}/${AWS_SDK_LIB_PATH}/${CMAKE_STATIC_LIBRARY_PREFIX}aws-cpp-sdk-xray${AWS_SDK_LIB_SUFFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
    ${INSTALL_DIR}/${AWS_SDK_LIB_PATH}/${CMAKE_STATIC_LIBRARY_PREFIX}aws-crt-cpp${AWS_SDK_LIB_SUFFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
)
set_target_properties(libawscpp PROPERTIES INTERFACE_INCLUDE_DIRECTORIES ${INSTALL_DIR}/include)
